### ISSUE TITLE
Install packages

### ISSUE THREAD

**Issue by hmok** [SoniaSong826/CAREN_OpenSim_Tools#4]
Hi Sonia,

I wonder if you can install all the relevant libraries. I got error when I install the libraries of pyosim, etc. Can you please check them out?

**Comment by SoniaSong826** [comment]
@hmok 
Yes! I execute the first cell, and there is an error. I haven't experienced this before. It really a disaster! I will try my best to fix it. ;-(
![image](https://user-images.githubusercontent.com/45267448/84668146-96d09b00-af66-11ea-9136-1a853cd4c889.png)

**Comment by hmok** [comment]
Yes, I think there is something to do with the installation of pyosim. The author might have changed something or something has been updated along the way. Feel free to contact pyosim authors as well. Thank you.

**Comment by SoniaSong826** [comment]
@hmok 
I asked the author of Pyomeca for the solution: https://github.com/pyomeca/pyomeca/issues/101 
I tried the command: `conda install pyomeca=2019.8 -c conda-forge` suggested , but it doesn't work.

`conda install -c conda-forge/label/cf202003 pyomeca` works in our project, I will update this in all files. I found this in https://anaconda.org/conda-forge/pyomeca
